# Generated by Django 4.1.3 on 2022-12-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commentable',
            field=models.BooleanField(null=True),
        ),
    ]
