# Generated by Django 4.1.3 on 2022-12-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_product_commentable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commentable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
